package app.spliit.android

import androidx.compose.ui.test.ExperimentalTestApi
import androidx.compose.ui.test.assert
import androidx.compose.ui.test.hasText
import androidx.compose.ui.test.junit4.createAndroidComposeRule
import androidx.compose.ui.test.onNodeWithTag
import androidx.compose.ui.test.onNodeWithText
import androidx.compose.ui.test.performClick
import androidx.compose.ui.test.performScrollTo
import androidx.compose.ui.test.performTextInput
import androidx.test.ext.junit.runners.AndroidJUnit4
import app.spliit.android.ui.TestTags
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith

/**
 * The one path that touches everything: create a group on a real server, find it on the
 * dashboard, open it, and look at each of its four tabs.
 *
 * **It creates its own group rather than reading a seeded one.** `make e2e-seed` writes fixture
 * groups, but their IDs are generated by the server and change on every seed, so a test naming
 * one is a test that passes until somebody re-seeds. Creating a group through the UI also
 * happens to exercise the half of the app a seeded fixture skips entirely — the form, the
 * mutation, the recent-groups write and the read back.
 *
 * The group's name carries a timestamp for the same reason: this suite runs against a **shared**
 * instance (CLAUDE.md: do not `make e2e-down` while something else is testing), so two runs must
 * not collide, and a failed run's leftovers must not make the next one ambiguous.
 *
 * Every wait is bounded. An unbounded one is how the iOS suite once turned a missing element
 * into a forty-minute CI job. The timeouts here are generous because each step is a real request
 * to a real server over the emulator's NAT.
 */
@OptIn(ExperimentalTestApi::class)
@RunWith(AndroidJUnit4::class)
class CreateGroupFlowTest {

    @get:Rule
    val rule = createAndroidComposeRule<MainActivity>()

    @Test
    fun aGroupCreatedHereCanBeOpenedAndEveryTabDrawsSomething() {
        val name = "E2E ${System.currentTimeMillis()}"

        // The dashboard offers creation in two places depending on whether it is empty. The FAB
        // is the one that is always there once anything has been added, and on a fresh install
        // the empty state's button is. Take whichever this device happens to show.
        rule.waitUntilAnyExists(
            TestTags.GROUPS_LIST_FAB,
            TestTags.GROUPS_LIST_EMPTY_CREATE_BUTTON,
            timeoutMillis = 20_000,
        )
        if (rule.exists(TestTags.GROUPS_LIST_FAB)) {
            rule.onNodeWithTag(TestTags.GROUPS_LIST_FAB).performClick()
        } else {
            rule.onNodeWithTag(TestTags.GROUPS_LIST_EMPTY_CREATE_BUTTON).performClick()
        }

        rule.waitUntilExists(TestTags.GROUP_FORM_SHEET)
        rule.onNodeWithTag(TestTags.GROUP_FORM_NAME_FIELD).performTextInput(name)

        // Two participants, because a one-person group has no split to make and would not
        // exercise the balances the group screen is mostly about.
        //
        // Two things make this loop fussier than it looks, both found on a device rather than
        // reasoned about: "Add participant" ends up under the keyboard once a row has been typed
        // into, so it is scrolled to before every click; and the row to type into is found by
        // being empty rather than by position, because the form re-sorts as you type.
        for (participant in listOf("Ana", "Bruno")) {
            rule.onNodeWithTag(TestTags.GROUP_FORM_ADD_PARTICIPANT_BUTTON)
                .performScrollTo()
                .performClick()
            rule.waitForIdle()
            // By name-of-what-is-in-it, not by position — see blankParticipantFieldTag.
            val field = rule.blankParticipantFieldTag()
            rule.onNodeWithTag(field).performScrollTo().performTextInput(participant)
            rule.waitForIdle()
        }

        rule.onNodeWithTag(TestTags.GROUP_FORM_SAVE_BUTTON).performClick()

        // Creating returns to the dashboard rather than opening the new group — see
        // GroupsListScreen's `onCreated`. So the first thing to assert is the row, which is also
        // the round trip worth having: typed into a form, written to the server, stored on the
        // device, and read back by the list.
        // Two waits, in this order, and both are load-bearing.
        //
        // The sheet dismisses itself only once the server has answered, so its disappearance is
        // the signal that creation actually succeeded — and waiting for anything on the
        // dashboard first races that dismissal. Waiting on the group's *name* is worse than
        // useless here: the sheet still displays it in its own "Group name" field, so that wait
        // is satisfied instantly while the dashboard behind is still empty.
        rule.waitUntilGone(TestTags.GROUP_FORM_SHEET, timeoutMillis = 20_000)
        rule.waitUntilExists(isGroupRow(), timeoutMillis = 20_000)

        // The device is wiped by the install that precedes each run, so the group just created
        // is the only one on the dashboard — hence `onNode` rather than picking one of several.
        // A second row would mean the previous run's state survived, and every assertion below
        // would be about the wrong group; `onNode` fails loudly on that rather than guessing.
        // The row really is the one just created — checked here, on the dashboard, rather than
        // after the tap: the group screen shows the same name in its app bar, so an assertion
        // made afterwards would pass whichever row had been tapped.
        rule.onNode(isGroupRow()).assert(hasText(name, substring = true))
        rule.onNode(isGroupRow()).performClick()

        // Each tab is opened, not merely present: three of the four fetch lazily, so a tab that
        // threw on its first load would otherwise go unnoticed.
        rule.waitUntilExists(TestTags.GROUP_DETAIL_TAB_EXPENSES, timeoutMillis = 20_000)
        for (tag in listOf(
            TestTags.GROUP_DETAIL_TAB_BALANCES,
            TestTags.GROUP_DETAIL_TAB_TOTALS,
            TestTags.GROUP_DETAIL_TAB_INFORMATION,
        )) {
            rule.onNodeWithTag(tag).performClick()
            rule.waitForIdle()
        }

        // Information is the last one opened above, and it names the participants this test
        // typed — read back by a different procedure from the one that wrote them.
        rule.waitUntilTextExists("Ana")
        // `assertExists`, not `assertIsDisplayed`: the participant list is near the top of a tab
        // that also carries the details, the activity link and the "You" picker, and on a short
        // screen the second name is already below the fold. What this is checking is that the
        // name round-tripped — typed into the form, written by one procedure, read back by
        // another — and scrolling to prove it would be testing the scroll container instead.
        rule.onNodeWithText("Bruno").assertExists()
    }
}
