package app.spliit.api

import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive

/**
 * The *shape* of a JSON document: every field path, paired with the kind of value it holds.
 *
 * This is what makes "the server changed" into "the server changed **this**". A decode failure
 * says a response no longer fits; a shape diff says `summary.averageExpense` went from a number
 * to a string, or that `recurring` appeared, which is the difference between a bug report and a
 * mystery.
 *
 * Paths look like `result.data.json.expenses[].paidBy.name`. Array indices collapse to `[]` on
 * purpose, the third expense having a field the first does not is a data difference, not a
 * schema one, and a shape keyed by index would report the length of a list as a breaking change.
 *
 * ### The two things it deliberately refuses to look at
 *
 * **An empty array.** `expenses: []` says nothing about what an expense looks like. Comparing a
 * recorded fixture that has rows against a live response that happens to have none would report
 * every field of an expense as removed. So an empty array contributes its own path and nothing
 * below it, and the comparison below prunes the other side to match.
 *
 * **A null.** Spliit nulls plenty of optional fields, and which ones are null depends on the
 * data rather than on the schema, `notes` is null on an expense without notes and a string on
 * one with. A null therefore records the path and no type, and never conflicts with a type.
 */
internal object JsonShape {

    /**
     * Objects whose **keys are values**, not field names.
     *
     * `groups.balances.list` answers with `balances` keyed by participant ID, and participant
     * IDs are generated by the server, so every run produces different ones. Walked as ordinary
     * objects, each key becomes its own path and the comparison reports one group's participants
     * as removed and another's as added: a wall of differences that is really just "these are
     * two different groups".
     *
     * Kept as an explicit list rather than guessed at from the shape of the keys. A heuristic -
     * "this looks like a nanoid", would quietly start collapsing a real field the day upstream
     * added one with a short opaque name, and the whole value of this check is that it does not
     * hide things.
     */
    private val DICTIONARY_PATHS = setOf("result.data.json.balances")

    /** A value's kind, as coarse as the wire is: JSON has no int-vs-long and neither does this. */
    internal enum class Kind { OBJECT, ARRAY, STRING, NUMBER, BOOLEAN, NULL, EMPTY_ARRAY }

    internal fun of(element: JsonElement): Map<String, Kind> {
        val out = sortedMapOf<String, Kind>()
        walk("", element, out)
        return out
    }

    private fun walk(path: String, element: JsonElement, out: MutableMap<String, Kind>) {
        when (element) {
            is JsonObject -> {
                out[path] = Kind.OBJECT
                // A dictionary's keys are data. Merged under `{}`, exactly as an array's
                // elements merge under `[]`, see DICTIONARY_PATHS.
                if (path in DICTIONARY_PATHS) {
                    for (value in element.values) walk("$path{}", value, out)
                    return
                }
                for ((key, value) in element) {
                    walk(if (path.isEmpty()) key else "$path.$key", value, out)
                }
            }

            is JsonArray -> {
                if (element.isEmpty()) {
                    out[path] = Kind.EMPTY_ARRAY
                    return
                }
                out[path] = Kind.ARRAY
                // Every element, merged: a list whose rows differ only by which optional fields
                // they carry should contribute the union, not whatever the first row happened to
                // have. Otherwise re-recording a fixture reshuffles the result.
                for (item in element) walk("$path[]", item, out)
            }

            is JsonNull -> out[path] = Kind.NULL

            is JsonPrimitive -> out[path] = when {
                element.isString -> Kind.STRING
                element.content == "true" || element.content == "false" -> Kind.BOOLEAN
                else -> Kind.NUMBER
            }
        }
    }

    /** One way the two shapes disagree, phrased for somebody reading a failed CI job. */
    internal data class Difference(val path: String, val describe: String)

    /**
     * What changed going from [recorded] to [live].
     *
     * Empty means the two agree. Order is stable so a diff of a diff is readable.
     */
    internal fun diff(recorded: Map<String, Kind>, live: Map<String, Kind>): List<Difference> {
        val pruned = pruneUnderEmptyArrays(recorded.withoutTransportMeta(), live.withoutTransportMeta())
        val recordedShape = pruned.first
        val liveShape = pruned.second
        val differences = mutableListOf<Difference>()

        for ((path, kind) in recordedShape) {
            val liveKind = liveShape[path]
            when {
                liveKind == null ->
                    differences += Difference(path, "gone, the fixture has it, the server no longer sends it")
                // A null on either side is data, not schema: see the note on this object.
                kind == Kind.NULL || liveKind == Kind.NULL -> Unit
                kind == liveKind -> Unit
                // An array that is empty on one side and populated on the other is data too.
                kind.isArray() && liveKind.isArray() -> Unit
                else -> differences += Difference(path, "was $kind, is now $liveKind")
            }
        }
        for (path in liveShape.keys) {
            if (path !in recordedShape) {
                differences += Difference(path, "new, the server sends it, the fixture has never seen it")
            }
        }
        return differences.sortedBy { it.path }
    }

    private fun Kind.isArray(): Boolean = this == Kind.ARRAY || this == Kind.EMPTY_ARRAY

    /**
     * Drops superjson's `meta`, which is not part of the contract this client reads.
     *
     * Two reasons, and the first alone would be enough. **The decoder ignores it**: CLAUDE.md
     * records why, the models are statically typed, so a field the server annotates as a date is
     * already declared one, and `groups.list` annotates nothing at all. **And it is keyed by
     * array index**, not by field: a response with four expenses carries
     * `meta.values.expenses.3.expenseDate` and one with a single expense does not, so comparing
     * it reports how much data each side happened to have as though it were a schema change.
     * That was the entire first output of this check, and it buried nothing real only because
     * there was nothing real to bury.
     */
    private fun Map<String, Kind>.withoutTransportMeta(): Map<String, Kind> =
        filterKeys { it != "result.data.meta" && !it.startsWith("result.data.meta.") }

    /**
     * Drops everything beneath an array that is empty on either side, from both sides.
     *
     * Without this, a live server with no activities yet would report every field of an activity
     * as removed, a difference about how much data exists rather than about the contract.
     */
    private fun pruneUnderEmptyArrays(
        recorded: Map<String, Kind>,
        live: Map<String, Kind>,
    ): Pair<Map<String, Kind>, Map<String, Kind>> {
        val emptyOnEitherSide = buildSet {
            for ((path, kind) in recorded) if (kind == Kind.EMPTY_ARRAY) add(path)
            for ((path, kind) in live) if (kind == Kind.EMPTY_ARRAY) add(path)
        }
        if (emptyOnEitherSide.isEmpty()) return recorded to live
        fun prune(shape: Map<String, Kind>) = shape.filterKeys { path ->
            emptyOnEitherSide.none { path.startsWith("$it[]") }
        }
        return prune(recorded) to prune(live)
    }

    /** The diff as the body of a failure message. */
    internal fun report(procedure: String, differences: List<Difference>): String = buildString {
        appendLine("The live server's `$procedure` no longer matches the recorded fixture:")
        appendLine()
        for (difference in differences) appendLine("  ${difference.path}: ${difference.describe}")
        appendLine()
        appendLine("If the change is expected, re-record with `make fixtures` and read the diff")
        appendLine("before committing it, a fixture updated without being read is a contract")
        appendLine("nobody is checking any more.")
    }
}
